// This file was automatically generated by noise-serde-lib.
import Foundation
import NoiseBackend
import NoiseSerde

public enum Record: Readable, Writable {
  case pong(Pong)
  public static func read(from inp: InputPort, using buf: inout Data) -> Record? {
    guard let id = UVarint.read(from: inp, using: &buf) else {
      return nil
    }
    switch id {
    case 0x0:
      return .pong(Pong.read(from: inp, using: &buf)!)
    default:
      return nil
    }
  }
  public func write(to out: OutputPort) {
    switch self {
    case .pong(let r): r.write(to: out)
    }
  }
}
public struct Pong: Readable, Writable {
  public init(
  ) {
  }
  public static func read(from inp: InputPort, using buf: inout Data) -> Pong? {
    return Pong(
    )
  }
  public func write(to out: OutputPort) {
    UVarint(0x0).write(to: out)
  }
}
public class Backend {
  let impl: NoiseBackend.Backend!
  init(withZo zo: URL, andMod mod: String, andProc proc: String) {
    impl = NoiseBackend.Backend(withZo: zo, andMod: mod, andProc: proc)
  }
  public func ping() -> Future<Pong> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Pong in
        return Pong.read(from: inp, using: &buf)!
      }
    )
  }
}
