// This file was automatically generated by noise-serde-lib.
import Foundation
import NoiseSerde

public enum Record: Readable, Writable {
  case ping(Ping)
  case pong(Pong)
  public static func read(from inp: InputPort, using buf: inout Data) -> Record? {
    guard let id = UVarint.read(from: inp, using: &buf) else {
      return nil
    }
    switch id {
    case 0x0:
      return .ping(Ping.read(from: inp, using: &buf)!)
    case 0x1:
      return .pong(Pong.read(from: inp, using: &buf)!)
    default:
      return nil
    }
  }
  public func write(to out: OutputPort) {
    switch self {
    case .ping(let r): r.write(to: out)
    case .pong(let r): r.write(to: out)
    }
  }
}
public struct Ping: Readable, Writable {
  public init(
  ) {
  }
  public static func read(from inp: InputPort, using buf: inout Data) -> Ping? {
    return Ping(
    )
  }
  public func write(to out: OutputPort) {
    UVarint(0x0).write(to: out)
  }
}
public struct Pong: Readable, Writable {
  public init(
  ) {
  }
  public static func read(from inp: InputPort, using buf: inout Data) -> Pong? {
    return Pong(
    )
  }
  public func write(to out: OutputPort) {
    UVarint(0x1).write(to: out)
  }
}
